---
title: "Create Cytoscape network for selected modules."
format: html
date: "2026-05-25"
bibliography: ../../../refs-stat-anal.bib
execute:
  fig-format: png
  fig.dpi: 300
---

## Rationale
The aim of this script is anutomatization of network creation in Cytoscape.

Built with R version `r getRversion()`

## R Preliminaries

Environment cleaning and set-up

```{r setup, include = FALSE}
# load package
library(RCy3)

# check connection to Cytoscape
cytoscapePing()

# Clean working directory
rm(list=ls())

library(paletteer)
library(dplyr)
```

```{r}
# read files

node_info = read.table("../results/wgcna/network/CytoscapeInput-nodes-brown-02.txt", header = TRUE, sep = "\t")
colnames(node_info)[3] = "module" # change column name

edge_info = read.table("../results/wgcna/network/CytoscapeInput-edges-brown-02.txt", header = TRUE, sep = "\t")
```


```{r cyto}
createNetworkFromDataFrames(
  title = "brown-01",
  collection = "leaf, ctrl, wgcna",
  nodes = node_info,
  node.id.list = "nodeName",
  source.id.list = "fromNode",
  target.id.list = "toNode",
  edges=edge_info
)
```

```{r node color}
column <- 'module'
values <- "brown"
colors <- values
setNodeColorMapping(column, values, colors,
                   mapping.type = "d")
```

```{r node shape}
setNodeShapeDefault('ELLIPSE')
```

```{r node size}
# run "Analyze network" to get degree values
analyzeNetwork()

column3 = "Degree"
setNodeSizeMapping(
  column3,
  c(1, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100),
  c(20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70),
  mapping.type="c"
)
```


```{r edge width}
column2 = "weight"

setEdgeLineWidthMapping(table.column = column2,
                        widths = c(1, 10))
```


```{r add annotation}
anno_file <- read.table("../../../input-data/go-uniprot/NAM-UP-anno", sep = "\t", header = FALSE, stringsAsFactors = FALSE)

loadTableData(anno_file, data.key.column="V1")
```

```{r save}
saveSession('test_turquoise') #.cys
```


:::{.callout-note}
The one problem is that there are multiple superfluous columns with identifiers.
:::

## References
